### PR TITLE
Add ability to select a specific diagram when XML contains multiple sheets

### PR DESCRIPTION
**Pull request by mainbrain**
Fix for issue #2

### CODE REVIEW

**Comment by languitar** [comment]
Thanks! Are you able to add a test for this functionality to the travis build?

**Comment by mainbrain** [comment]
I don't know how. 

I found a single test in your package.json 
`"test": "node drawio-batch.js ./drawio/src/main/webapp/templates/uml/uml_1.xml test.pdf && file test.pdf | grep 'PDF document'"`
which basically uses one of the drawio templates to render a PDF file.

**Question 1:**
How can I add another test? Never worked with Travis and the package.json seems to be hard wired for a single test. There seems to be no jest or anything comparable.

**Question 2:**
There are no XML files with multiple sheets
`grep -c -r "<diagram" . | grep xml | grep -v ":0" | grep -v ":1"`
In which folder should I create a demo.xml file? It doesn't make sense to use the drawio folder.

demo.xml
`<mxfile userAgent="Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36" version="8.5.13" editor="www.draw.io" type="device"><diagram id="6a6edbf6-347e-32b6-c565-505b942d67d4" name="Page-1">jZNNb4MwDIZ/Te6FbGi7wrrtMu3Qw84puCRaiFGaDtivnykOH6oqjQvxYzuJXztCFk3/5lWrP7ACK9Jd1Qv5ItI02T2k9BvJMJEse5xA7U3FQQs4mF+ImUwvpoLzJjAg2mDaLSzROSjDhinvsduGndBuT21VDTfgUCp7S79MFTTTJHteHO9gas1HP6XZ5Diq8rv2eHF8nkjl6fpN7kbFvbjQs1YVdisk90IWHjFMq6YvwI7aRtmmvNc73vneHlz4TwL36UfZC5f+6YCvFoYox7UgGFN2QuadNgEOrSpHb0cDQEyHxpKV0NKqI9h81qFAi55cDmljmZ+MtREt4hBHF3gOEkm2sqZ2ZJRUCFBwzhcFH6C/W2wyS0ijCdhA8AOF9NvpGrZmt+pw7IteNTdjpnio6nnjRVhasLbRXHp49a0eitz/AQ==</diagram><diagram id="5d6f108f-2ce3-f7ff-e88e-b9b65cdbfb3a" name="Page-2">jZNNb4MwDIZ/Te6FbGi7wrrtslMn7ZyCS6KFGKXpgP36meLwoarSuBA/tpP4tSNk0fRvXrX6AyuwIt1VvZAvIk2T3UNKv5EME8myxwnU3lQctICD+YWYyfRiKjhvAgOiDabdwhKdgzJsmPIeu23YCe321FbVcAMOpbK39MtUQTNNsufF8Q6m1nz0U5pNjqMqv2uPF8fniVSert/kblTciws9a1Vht0JyL2ThEcO0avoC7KhtlG3Ke73jne/twYX/JHCffpS9cOmfHfLVwhDluBYEY8pOyLzTJsChVeXo7WgAiOnQWLISWlp1BJvPOhRo0ZPLoaP4/GSsjWgRhzi6wHOQSLKVNbUjo6RCgIJzvij4AP3dYpNZQhpNwAaCHyik307XsDW7VYdjX/SquRkzxUNVzxsvwtKCtY3m0sOrb/VQ5P4P</diagram></mxfile>`

**Comment by languitar** [comment]
I am fine with just chaining another call in the travis command line that is executed (using `&&`). You can add a "test" folder to the repository for the sample file. It would be good if the call checks that the correct page is exported. Maybe using `grep` on the generated PDF works?

**Comment by mainbrain** [comment]
Added test file. I cant do the test though because I'd have to check for pdf contents, which is not possible via grep. So `"test2": "node drawio-batch.js --diagramId 2 ./test/multipleSheets.xml multipleSheetTest.pdf && grep -a 'BoxOnSheetTwo' multipleSheetTest.pdf"` doesn't work.

I'd have to have pdfgrep or something similar available.

Another alternative would be to use PDF.js. But frankly speaking, that would exceed my time budget :)

**Comment by languitar** [comment]
Thanks for adapting this! `pdfgrep` should be fine. I will have a look at how to integrate this soon.

**Comment by languitar** [comment]
Sorry for the delay. Now it works.

**Pull request closed without merging**
